# Generated by Django 5.1.4 on 2025-04-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp_id', models.CharField(max_length=32, unique=True)),
                ('user', models.CharField(max_length=64)),
                ('redirect_url', models.URLField()),
                ('thumb_url', models.URLField()),
                ('alt_text', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
