# Generated by Django 5.1.4 on 2025-04-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_video_is_banned_user_video_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tweet_url',
            field=models.URLField(blank=True),
        ),
    ]
