# Generated by Django 5.1.4 on 2025-04-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_video_tweet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='ユーザーがアップロードした動画ファイル', null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_banned_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='pin_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
